/* automatically generated by rust-bindgen 0.72.1 */

unsafe extern "C" {
    pub fn hfst_empty_transducer() -> *mut ::std::os::raw::c_void;
}
pub type hfst_empty_transducer_t =
    ::std::option::Option<unsafe extern "C" fn() -> *mut ::std::os::raw::c_void>;
unsafe extern "C" {
    pub fn hfst_input_stream(path: *const ::std::os::raw::c_char) -> *mut ::std::os::raw::c_void;
}
pub type hfst_input_stream_t = ::std::option::Option<
    unsafe extern "C" fn(filename: *const ::std::os::raw::c_char) -> *mut ::std::os::raw::c_void,
>;
unsafe extern "C" {
    pub fn hfst_input_stream_close(input_stream: *const ::std::os::raw::c_void);
}
pub type hfst_input_stream_close_t = ::std::option::Option<
    unsafe extern "C" fn(arg1: *mut ::std::os::raw::c_void) -> *mut ::std::os::raw::c_void,
>;
unsafe extern "C" {
    pub fn hfst_input_stream_is_eof(arg1: *const ::std::os::raw::c_void) -> bool;
}
pub type hfst_input_stream_is_eof_t =
    ::std::option::Option<unsafe extern "C" fn(arg1: *mut ::std::os::raw::c_void) -> bool>;
unsafe extern "C" {
    pub fn hfst_input_stream_is_bad(arg1: *const ::std::os::raw::c_void) -> bool;
}
pub type hfst_input_stream_is_bad_t =
    ::std::option::Option<unsafe extern "C" fn(arg1: *mut ::std::os::raw::c_void) -> bool>;
unsafe extern "C" {
    pub fn hfst_transducer_from_stream(
        input_stream: *const ::std::os::raw::c_void,
    ) -> *mut ::std::os::raw::c_void;
}
pub type hfst_transducer_from_stream_t = ::std::option::Option<
    unsafe extern "C" fn(arg1: *mut ::std::os::raw::c_void) -> *mut ::std::os::raw::c_void,
>;
unsafe extern "C" {
    pub fn hfst_lookup_begin(arg1: *const ::std::os::raw::c_void) -> *mut ::std::os::raw::c_void;
}
pub type hfst_lookup_begin_t = ::std::option::Option<
    unsafe extern "C" fn(arg1: *const ::std::os::raw::c_void) -> *mut ::std::os::raw::c_void,
>;
unsafe extern "C" {
    pub fn hfst_lookup_results(
        arg1: *const ::std::os::raw::c_void,
        arg2: *mut *mut ::std::os::raw::c_char,
        arg3: *mut f32,
    ) -> usize;
}
pub type hfst_lookup_results_t = ::std::option::Option<
    unsafe extern "C" fn(
        arg1: *mut ::std::os::raw::c_void,
        arg2: *mut *mut ::std::os::raw::c_char,
        arg3: *mut f32,
    ) -> usize,
>;
unsafe extern "C" {
    pub fn hfst_lookup(
        transducer: *mut ::std::os::raw::c_void,
        input: *const ::std::os::raw::c_char,
    ) -> *mut ::std::os::raw::c_void;
}
pub type hfst_lookup_t = ::std::option::Option<
    unsafe extern "C" fn(
        arg1: *mut ::std::os::raw::c_void,
        arg2: *const ::std::os::raw::c_char,
    ) -> *mut ::std::os::raw::c_void,
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ResultIterator {
    pub begin: *mut ::std::os::raw::c_void,
    pub end: *mut ::std::os::raw::c_void,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ResultIterator"][::std::mem::size_of::<ResultIterator>() - 16usize];
    ["Alignment of ResultIterator"][::std::mem::align_of::<ResultIterator>() - 8usize];
    ["Offset of field: ResultIterator::begin"]
        [::std::mem::offset_of!(ResultIterator, begin) - 0usize];
    ["Offset of field: ResultIterator::end"][::std::mem::offset_of!(ResultIterator, end) - 8usize];
};
unsafe extern "C" {
    pub fn hfst_lookup_iterator(lookup: *mut ::std::os::raw::c_void) -> *mut ResultIterator;
}
pub type hfst_lookup_iterator_t = ::std::option::Option<
    unsafe extern "C" fn(arg1: *mut ::std::os::raw::c_void) -> *mut ResultIterator,
>;
unsafe extern "C" {
    pub fn hfst_lookup_iterator_value(
        it: *mut ResultIterator,
        s: *mut *mut ::std::os::raw::c_char,
        w: *mut f32,
    );
}
pub type hfst_lookup_iterator_value_t = ::std::option::Option<
    unsafe extern "C" fn(
        it: *mut ResultIterator,
        s: *mut *mut ::std::os::raw::c_char,
        weight: *mut f32,
    ),
>;
unsafe extern "C" {
    pub fn hfst_lookup_iterator_next(it: *mut ResultIterator);
}
pub type hfst_lookup_iterator_next_t =
    ::std::option::Option<unsafe extern "C" fn(arg1: *mut ResultIterator)>;
unsafe extern "C" {
    pub fn hfst_lookup_iterator_free(it: *mut ResultIterator);
}
pub type hfst_lookup_iterator_free_t =
    ::std::option::Option<unsafe extern "C" fn(it: *mut ResultIterator)>;
unsafe extern "C" {
    pub fn hfst_lookup_iterator_done(it: *mut ResultIterator) -> bool;
}
pub type hfst_lookup_iterator_done_t =
    ::std::option::Option<unsafe extern "C" fn(it: *mut ResultIterator) -> bool>;
